### ISSUE TITLE
Compiled problem crystal 0.31.1

### ISSUE THREAD

**Issue by bglobalnet** [niieani/hashids.js#144]
Hi,

Installed the crystal version 0.31.1, but when I compile the code I received this error:

883 | hash = hashids.encode([theId])
^-----
Error: instantiating 'Hashids#encode(Array(Int32))'

In lib/hashids/src/hashids.cr:30:5

30 | _encode(numbers)
^------
Error: instantiating '_encode(Array(Int32))'

In lib/hashids/src/hashids.cr:72:14

72 | last = _to_alphabet(number, alphabet)
^-----------
Error: instantiating '_to_alphabet(Int32, String)'

In lib/hashids/src/hashids.cr:169:5

169 | loop do
^---
Error: instantiating 'loop()'

In lib/hashids/src/hashids.cr:169:5

169 | loop do
^---
Error: instantiating 'loop()'

In lib/hashids/src/hashids.cr:170:21

170 | id << alphabet[input % alphabet.size]
^
Error: no overload matches 'String#[]' with type (Float64 | Int32)

Overloads are:

    String#[](start : Int, count : Int)
    String#[](regex : Regex, group)
    String#[](index : Int)
    String#[](range : Range)
    String#[](str : String | Char)
    String#[](regex : Regex)
    Couldn't find overloads for these types:
    String#

Thank you,

**Comment by niieani** [comment]
Hi @bglobalnet. This is a repo for a JavaScript version. Please open an issue in the respective version.
