### ISSUE TITLE
Custom curse list / seps

### ISSUE THREAD

**Issue by dshivak** [niieani/hashids.js#17]
Can an argument be added to override the default hardcoded sep list of characters, or better yet, do a check against a full custom curse list?  The sep list character removal may cause estimates of the number of characters needed to be wrong.  A custom curse list would also allow non-English speakers to avoid curses in other languages.

**Comment by ivanakimov** [comment]
Hi @dshivak, sorry for late response. Yes, I think a custom separator list would be nice to have. A custom curse list might be a bit "too-specific" to implement, but an extra parameter to the constructor to replace the sep list might be just fine.

I'll queue it up for next release.

**Comment by raviteja1239** [comment]
HI, 

I have tried to generate hash for two salts, But for both i have received same hash

Salt 1 : 

var hashids = new Hashids("8415", 6, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");

var id = hashids.encode(2, 4, 3);
var numbers = hashids.decode(id);

Generated Hash : e2c7fo

Salt 2 : 

var hashids = new Hashids("17871", 6, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");

var id = hashids.encode(2, 4, 3);
var numbers = hashids.decode(id);

Generated Hash : e2c7fo


![image](https://cloud.githubusercontent.com/assets/14074956/9606035/bcbd2018-50de-11e5-9c8e-a9b202dbf10b.png)

![image](https://cloud.githubusercontent.com/assets/14074956/9606064/da30f836-50de-11e5-896f-5cedc4c5fc6f.png)


Is there any best way to avoid collisions to generate the hash? Help me on this.

**Comment by tmorehouse** [comment]
Hashes are only guaranteed to be unique when the same salt is used.

**Comment by raviteja1239** [comment]
Dear tmorehouse, i have given different different salts, 


var hashids = new Hashids("17871", 6, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");
var hashids = new Hashids("8415", 6, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");

Can you tel me what i have to change here?
I want to generate the unique hashes from digit 1 to 10000000 serially, can you help?

**Comment by ivanakimov** [comment]
@raviteja1239, go over the documentation, especially this part: http://hashids.org/#collisions

@tmorehouse has given you exactly the right answer. There is no problem, you just have to use the same salt while you're generating ids.

**Comment by raviteja1239** [comment]
@ivanakimov @tmorehouse  - Working! Thanks for your support.

**Comment by raviteja1239** [comment]
Hi @ivanakimov  @tmorehouse 

Now I tried to generate the hashes[6 Character] for numbers 0.5 billion with same salt,
But am able to generate up to 164916223 hashes with six char, and for the number 164916224 i have received 7 character hash.

As per the common scenario 62! means [A-Z,a-z,0-9] 62^6 = almost 57 billion unique values possible.
Can you suggest me any idea to generate 6 character hashes without any collision.

**Comment by tmorehouse** [comment]
With a minimum 6 character hash, there are actually only a minimum of 5 characters that are used to encode the value. the first character is a seed value to store the "lottery" value for the sorting. 

If you would like to ensure that the hash is only 6 characters for that last large number, add additional characters to your alphabet (say add in `_`, `-`, etc.) to reduce the resulting hash length.

There is no way to actually force a maximum hash length.

**Comment by raviteja1239** [comment]
Hi @tmorehouse 

Can you give and example for this,
"If you would like to ensure that the hash is only 6 characters for that last large number, add additional characters to your alphabet (say add in _, -, etc.) to reduce the resulting hash length."

And is there any chance to give alphanumeric encoding for the hash generation? like 1a,1b,1c...

var hashids = new Hashids("Rav1T3jA", 6, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");
var id = hashids.encode(1a);
var numbers = hashids.decode(id);

Thanks for your support!

**Comment by tmorehouse** [comment]
HashIds only encodes numbers, you cannot encode letters.  HashIds does support encoding hex numbers as well (separate encode and decode functions though). 

As per my coment about hte alphabet:

    var hashids = new Hashids(
        "Rav1T3jA",
        6,
        "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_-~`!@#$%^&*()_+-|{}[]:;/?<>");

would generate shorter hashes (since there are mote characters to choose from)

Note that some characters given in the above example may not be URL safe

**Comment by raviteja1239** [comment]
@tmorehouse 

If i give special characters, hash may generate with those chars.
Is there any other way to generate the unique hashes[without collision] in 6 characters?

**Comment by tmorehouse** [comment]
Not using the hashid's library.

Maybe you should use BASE64 or BASE62 encoding of your numbers and pad the end (with non base 64 or base 62 characters) to make it 6 characters in length.

**Comment by hustcer** [comment]
+1 for the `custom curse list` feature

**Comment by cupliz** [comment]
could you tell me how to disable curse feature? thanks
