### ISSUE TITLE
Version 2.2.1 does not work with Node v13.6.0

### ISSUE THREAD

**Issue by peterviergutz** [niieani/hashids.js#209]
Hi,

while upgrading my projects dependencies I noticed that the latest version produces errors with NodeJS v13.x:

```
Error: Package exports for '/.../node-helpers/node_modules/hashids' do not define a valid './cjs' target
```

see https://runkit.com/peavey/version-2-2-1-does-not-work-with-nodejs-v13-x

Cheers,
Peter

**Comment by stefandesu** [comment]
Having the same issue. Supposedly it was fixed in 2.2.1 (#207), but it's not working for me.

**Comment by CuriousLearner** [comment]
Hey @niieani 

Do we have any update on this? I'm not able to import this library in nodejs

**Comment by nickmeessen** [comment]
Not exactly a fix, but it seems to work when using a newer version of Node, not sure which exact version(s) of Node are incompatible, but while using 13.8+ the library works as expected.

**Comment by svobik7** [comment]
Same for me. Using Node 12.14.1 and Hashids 2.2.1 creates following error:

```
[ error ] /.../node_modules/hashids/esm/index.js:280
export { Hashids as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

Any chance to fix to work with older Node in future relases?

**Comment by niieani** [comment]
@svobik7 I think you want to use the CJS version: `require('hashids/cjs')`. See README for more info.

**Comment by niieani** [comment]
Please use latest hashids, or either v12 or v14 of node.
