### ISSUE TITLE
Hash max length

### ISSUE THREAD

**Issue by ansdma** [niieani/hashids.js#3]
Is it possible to set the hash maximum length?

**Comment by aleris** [comment]
It is not immediately obvious (to me) how the length of the input numbers determine the length of the result id. If I need the result id to be, for example, maximum 24 characters, what would be the maximum input number or numbers (obviously in relation with the alphabet)?

**Comment by tmorehouse** [comment]
You would need to test it out with the alphabet you have chosen. If you are usinghte javascript library, the maximum integer that javascript can handle is +/- 9,007,199,254,740,991 (the largest number stored in a float before precision is lost - see [ECMA Section 8.5 - Numbers](http://ecma262-5.com/ELS5_HTML.htm#Section_8.5)).

So set up your alphabet and salt, and then enter in 9007199254740991 as the ID to encode. Then you can get the length of the hashid returned.

**Comment by djibarian** [comment]
I thought using the formula `Math.log(# of numbers) / Math.log(alphabet size)` could give me the number of output digits (like in `Math.log(0x100000000) / Math.log(16)` gives 8 digits for an hex alphabet and a 32-bit unsigned integer), but it seems not to be the case.

So I’m lost in a way of calculating the maximum number of output digits without the test/error solution proposed by @tmorehouse. An explanation about the relationship between input, alphabet and output digits would be appreciated.
