### ISSUE TITLE
hashids/cjs does not work with webpack 5

### ISSUE THREAD

**Issue by jsiddiqui** [niieani/hashids.js#333]
Webpack 5 has an ExportFieldPlugin (https://github.com/webpack/enhanced-resolve/pull/214/files) but it seems to be looking for "default" or "browser" instead of "import" or "require" and hence the "./cjs" export does not work. If we can add a "default" entry to "./cjs" export in package.json, it will work with webpack 5. v2.1.0 still works since it does not have the import/require fields.

**Comment by niieani** [comment]
Hey @jsiddiqui thanks for flagging this. I think this is an issue with webpack's implementation, since this is defined correctly [according to NodeJS documentation](https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_conditional_exports). Would you mind creating an issue in the enhanced-resolve repo?

We could also add a `default` fallback, since it's valid in either case. I'm torn on whether we should be pointing it to CJS or the Module version, though.

Thanks 🙇

**Comment by jsiddiqui** [comment]
Thanks for the quick response. I do not think webpack is wrong in this case, as it is bundling for the browser so looking for the browser key (or default) and not the NodeJS keys. According to the specs you linked, other environments like browser use their own keys. 

Secondly, I was talking about a default entry _inside_ the "./cjs" entry---not a top-level default entry. I think it would be the right choice to point it to CJS for anyone explicitly asking for hashids/cjs

**Comment by niieani** [comment]
OK, sounds good. Would you send a PR? You can edit the file from the GitHub UI if you don't want to clone the repo.

I'd still want to flag this with @sokra to get his point of view, since this will probably show up as a problem in other packages.

**Comment by sokra** [comment]
Webpack also uses import and require conditions just like node.

The ./cjs export has only a `require` condition which only makes `require("hashids.js/cjs")` valid and `import "hashids.js/cjs"` is not valid and leads to a resolve error.

For the `.` export note that conditions are matching in order, so the `browser` condition should come before `import` and `require`.

**Comment by jsiddiqui** [comment]
Hmmm. Right. So we need to add `import` to the `./cjs` entry or more simply just replace the `require` with `default` for that one entry. I'll send a PR with the `.` export fix as well.

**Comment by jsiddiqui** [comment]
I see. Moving `browser` first in `.` export actually fixes the need to change anything else. I was using `/cjs` import with webpack to avoid transpiling dependencies, but with the corrected order, webpack will use the `browser` entry even for the `.` export and if `target: node` is chosen in webpack, then an entry according to `import` or `require` is used.

**Comment by niieani** [comment]
Amazing, thanks for the input and clarification Tobias! It might be worth clarifying this in the webpack docs.

And thanks for the PR, Junaid!
