### ISSUE TITLE
Field main in package.json incorrectly refers to ESM, not CJS version

### ISSUE THREAD

**Issue by tkalliom** [niieani/hashids.js#352]
From the `npm` documentation:
> The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned.

Since `require` operates on CJS modules, it makes no sense to declare an ESM main. Instead of `"main": "esm/index.js"`, `hashids` should have `"main": "cjs/index.js"`.

A consequence of this that we hit is that on older (but still LTS) versions of Node.js which do not have the `exports` mechanism, doing `require("hashids")` attempts to load `hashids/esm/index.js`, which fails due to that file being ESM, unsupported by Node.js. (We use TypeScript. The failure just mentioned occurs when we try to run our transpiled tests. We can’t directly load the module `hashids/cjs` either, since for our production build we use Rollup, the `plugin-node-resolve` of which was recently updated to respect `exports`, so it does not rollup subpaths not listed in `exports`)

**Comment by niieani** [comment]
Thanks for the detailed report @tkalliom!
