### ISSUE TITLE
Export typescript definitions instead of source

### ISSUE THREAD

**Issue by davazp** [niieani/hashids.js#418]
Using the latest release 2.2.8,  the typescript definition file in the package is defined like

```
import Hashids from '../lib/hashids'

export = Hashids
```

with that import to the source code. Unfortunately, this is less robust than building Typescript and including the definitions only, as the success of the build depends on the user having a compatible Typescript configuration.

For example, we use the recent `"noUncheckedIndexedAccess": true` flag, with breaks the code.

Most libraries built the Typescript in the output with `declarations: true`, so the user does not have to build it from the source.

**Comment by zachrip** [comment]
TS maintainers also recommend against shipping ts to consumers of an npm package. I had to disable certain rules in order to get hashids to work despite having `skipLibCheck` set to true which baffled me. Was surprised to see a .ts file in /lib.

**Comment by niieani** [comment]
@davazp I agree with using a definition file instead; I just didn't have time to set it up and re-exported the .ts instead as a workaround. Open to PRs that introduce this. The thing is it will have to be present in each folder that contains the built version.

@zachrip I am of a different point of view regarding shipping source code. I think it can be quite beneficial; in this case it's a single file so I'd like to keep it.

**Comment by Xetera** [comment]
Is there a way to disable this somehow? I'm forced to disable strict checks at the moment which I really don't want to have to do for a single library. I tried downgrading all the way to 1.2.2 but it seems like this library has been shipping typescript source for a while now.

**Comment by niieani** [comment]
@Xetera best way is disable type checking in node_modules, there's a tsconfig flag for this.

**Comment by niieani** [comment]
Fixed in v2.2.9
