### ISSUE TITLE
my hash info

### ISSUE THREAD

**Issue by cid8809** [niieani/hashids.js#454]
<html>
<head>
<title>id</title>
</head>

<body>
<p>hello</p>

<script type="text/javascript">
    function create_UUID() {
        var dt = new Date().getTime();
        var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = (dt + Math.random()*16) % 16 | 0;
            dt = Math.floor(dt / 16);
            return (c == 'x' ? r : (r&0x3|0x8)).toString(16);
        });
        return uuid;
    }
</script>

<script type="text/javascript" src="hashids.min.js"></script>

<script type="text/javascript">
    function hash_info(uuid) {
        console.log(uuid);
        var hashids = new Hashids(uuid);
        var id = hashids.encode(['1','2','3','5','6','7','8','9','10','0']);
        console.log(id);
        //console.log(hashids);
        //console.log(hashids.decode(id));
        console.log(hashids.salt.join().replaceAll(",",""));
    }
</script>
<script type="text/javascript">
    var uuid = create_UUID();
    hash_info(uuid);
</script>

</body>

</html>

**Comment by niieani** [comment]
?

**Comment by cid8809** [comment]
thank you all.
