### ISSUE TITLE
Pen linked from home page doesn't work

### ISSUE THREAD

**Issue by tomchiverton** [niieani/hashids.js#481]
https://codepen.io/anon/pen/vqGmBX just says "ReferenceError: Hashids is not defined" because is no import

**Comment by tomchiverton** [comment]
![Screenshot_20211201_091952](https://user-images.githubusercontent.com/684204/144206798-d9934de4-9d18-4421-8417-2c7109f8de83.png)

**Comment by niieani** [comment]
Ah, it needs to be updated to the [codesandbox](https://codesandbox.io/s/hashids-demo-54qvc?fontsize=14&hidenavigation=1&module=%2Fsrc%2Findex.ts&theme=dark).
Thanks for flagging.

**Comment by niieani** [comment]
Can you post this issue (or a PR with the fix) to the repo of the website?  https://github.com/hashids/hashids.github.io

**Comment by tomchiverton** [comment]
https://github.com/hashids/hashids.github.io/pull/78
