### ISSUE TITLE
PHP lib is broken. Empty encode result.

### ISSUE THREAD

**Issue by alexburets** [niieani/hashids.js#509]
For example:

$hash = '00002adfc6fc871a'; // also 200002ad string
$hashids = new Hashids\Hashids('00002adfc6fc871a00002adfc6fc871a');
$id = $hashids->encode($hash);
var_export($id);

I have database with 360114 rows like '00002adfc6fc871a'
Same empty result for 359931 rows for any salt.

More string examples: 
00004772dd1885d8
000074c40e98c75e
00007cfdb3f19f93
000082bb1a4b07a7
000111ce191a3854
00011c3b974bb079
0001280c9f015a28
000153c3ed413676
0001800b3589a0cb
0001aebb875f5a57

**Comment by miquelfire** [comment]
Wrong repo, you want https://github.com/vinkla/hashids
