### ISSUE TITLE
encode more than 16 digits

### ISSUE THREAD

**Issue by sebolio** [niieani/hashids.js#523]
Hi, i'm trying to encode a long id (20 digits) but hashids.encode returns empty, what can i do?

**Comment by niieani** [comment]
Any number that's greater than 2^53 is too large to be represented accurately in JavaScript as an integer. This isn't a problem of the library, but of JavaScript. Use a BigInt instead: [example](https://codesandbox.io/s/hashids-demo-bigint-b0sfty?file=/src/index.ts).
