### ISSUE TITLE
Getting duplicate hash id with different salt but same encode value

### ISSUE THREAD

**Issue by AbhishekTaparia** [niieani/hashids.js#549]
Hi I am facing a issue where I am getting same hash id for different salts but same encode value.
Below is the code:

```javascript
import Hashids from 'hashids/cjs/hashids';
...
generateShortID(salt: string): string {
    return new Hashids(salt).encode(1);
}
```

Getting same result for below:
```javascript
generateShortID('646f0eeda16c1feb3feb8321');
generateShortID('646f0eeda16c1feb3feb8330');

// Result for both - Gn
```

**Comment by niieani** [comment]
There's no guarantee that a different salt will necessarily output a different ID, esp. for small numbers, like 1.
@miquelfire's answer is correct.
