### ISSUE TITLE
Output differs from .net implementation

### ISSUE THREAD

**Issue by chrisfoster76** [niieani/hashids.js#64]
Up until now I have found that hashids.js produces the same output as the .net implementation given the same input. I am aware of issues around large numbers (https://github.com/ivanakimov/hashids.js/issues/23), but this seems to occur for any number.

The following:

```
var salt = 'this is my salt';
var alphabet = '46789BCDFGHJKLMNPRSTVWX';
var minLength = 6;
var encoder = new Hashids(salt, minLength, alphabet);
var result = encoder.encode(1);
```

Gives `NKPGJ7` in .net but `9VRNM7` in .js.

Curiously, removing the X at the end of the alphabet returns the same from both.

**Comment by niieani** [comment]
My hunch is that this is somehow a bug in the .NET implementation. But we'd need to verify this with more tests. Not sure which is the reference implementation @ivanakimov?

**Comment by manigandham** [comment]
@niieani 

This is an old issue but the .NET version has been recently updated and I've confirmed the hash ids match up to the JS version, 

https://www.nuget.org/packages/Hashids.net

**Comment by cuixiping** [comment]
This issue should be closed now.

**Comment by niieani** [comment]
Thanks @manigandham and @cuixiping!
