### ISSUE TITLE
Unexpected token export with v2

### ISSUE THREAD

**Issue by giladno** [niieani/hashids.js#73]
```
test_project/node_modules/hashids/esm/index.js:270
export { Hashids as default };
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by niieani** [comment]
Hi @giladno. Since this is a major version bump, please ensure to read the CHANGELOG / release notes.

There was a breaking change that requires you to change the way you `require` Hashids from node. Try:

```js
const Hashids = require('hashids/cjs')
const hashids = new Hashids()
```

Note the `/cjs` path.

See: https://github.com/niieani/hashids.js#getting-started

**Comment by PachowStudios** [comment]
What was the reasoning behind this change? This is pretty much the only package I know of that requires importing from a cjs submodule specifically for node environments.

**Comment by niieani** [comment]
@PachowStudios it's actually one of the recommended ways to support both ES Modules and CommonJS from a single package. See [this bit](https://nodejs.org/api/esm.html#esm_package_entry_points) of official NodeJS documentation, specifically:

> The "main" field can point to exactly one file, regardless of whether the package is referenced via require (in a CommonJS context) or import (in an ES module context). Package authors who want to publish a package to be used in both contexts can do so by setting "main" to point to the CommonJS entry point and informing the package’s users of the path to the ES module entry point. Such a package would be accessible like require('pkg') and import 'pkg/module.mjs'. Alternatively the package "main" could point to the ES module entry point and legacy users could be informed of the CommonJS entry point path, e.g. require('pkg/commonjs').

Modules by default are favorable due to how bundlers like webpack and rollup work.

**Comment by PachowStudios** [comment]
@niieani Isn't that what the "module" field is for? Bundlers use that field over "main" if it exists.

**Comment by niieani** [comment]
@PachowStudios "module" sadly isn't official and wasn't implemented by the NodeJS module loader.
