### ISSUE TITLE
SyntaxError: Unexpected token export when using require

### ISSUE THREAD

**Issue by jpike88** [niieani/hashids.js#78]
https://github.com/niieani/hashids.js/blob/c6659c4334b2f346605e982de23890b44a1be4f4/esm/index.js#L270

I get an error trying to run it in JS when trying to require it with the following code:

```
const Hashids = require("hashids").default;
```

Below is the error:

```
export { Hashids as default };
^^^^^^

SyntaxError: Unexpected token export
```

This worked fine on 1.2.2, upgrading to 2.0.0 caused the break.

**Comment by jpike88** [comment]
never mind, saw the closed issue already addressing this

**Comment by davehowson** [comment]
Could you at least link the closed issue before closing this?

**Comment by kenanaKYD** [comment]
Here's the link to the closed issue where it says how to solve this:
https://github.com/niieani/hashids.js/issues/158#issuecomment-566290969
