### ISSUE TITLE
How to import hashids v2 in Angular/Typescript?

### ISSUE THREAD

**Issue by anisabboud** [niieani/hashids.js#90]
1. **import from 'hashids'** doesn't work (Cannot find name 'BigInt'):
```
import Hashids from 'hashids';
import * as Hashids from 'hashids';
import { default as Hashids } from 'hashids';

ERROR in node_modules/hashids/lib/hashids.ts(132,28): error TS2554: Expected 0 arguments, but got 1.
node_modules/hashids/lib/hashids.ts(163,29): error TS2304: Cannot find name 'BigInt'.
```
![image](https://user-images.githubusercontent.com/5672108/64610242-7ff98880-d3d7-11e9-8d6c-00b05e69a7c9.png)

2. **import from 'hashids/cjs'** doesn't work either:
```
import Hashids from 'hashids/cjs';
import { Hashids } from 'hashids/cjs';
import * as Hashids from 'hashids/cjs';

This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.ts(2497)
index.d.ts(3, 1): This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

3. **require('hashids/cjs')** works only if I declare require (even though @types/node is installed):
```
const Hashids = require('hashids/cjs');

error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field 
```

This works, but doesn't have the Typescript typings: 
```
declare var require: any;
const Hashids = require('hashids/cjs');
```

(With v1, I was using `import Hashids from 'hashids';` with `@types/hashids` installed.)

**Comment by j-f1** [comment]
It seems like you don’t have the appropriate `lib` set to enable TypeScript support for `BigInt`. Maybe your TS version is out of date?

**Comment by anisabboud** [comment]
Thank you, @j-f1.
I have Typescript version 3.5.2 and [BigInt was introduced in 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint).
It's recognized inside VS Code, but when I run `ng serve` I get console errors and "Failed to compile."

![image](https://user-images.githubusercontent.com/5672108/64614566-6cebb600-d3e1-11e9-8193-286db08075a5.png)

**Comment by niieani** [comment]
In your `tsconfig.json` you need to ensure you have `esnext.bigint` included as one of the `lib`s:

```json
{
  "compilerOptions": {
    "lib": [
      "esnext.bigint"
    ]
  }
}
```

**Comment by anisabboud** [comment]
Adding `"esnext.bigint"` or [`"esnext"`](https://github.com/microsoft/TypeScript/blob/master/src/lib/esnext.d.ts) to `tsconfig.json` worked with `import Hashids from 'hashids';`
Thank you!

Perhaps a note about Typescript should be added to the Get Started guide
https://github.com/niieani/hashids.js#getting-started

**Comment by niieani** [comment]
@Johann-S Indeed, want to post a PR? :)
